import {
    createDefaultModule, createDefaultSharedModule, DefaultSharedModuleContext, inject,
    LangiumServices, LangiumSharedServices, Module, PartialLangiumServices
} from 'langium';
import { ShapeGeneratedModule, ShapeGeneratedSharedModule } from './generated/module';
import { ShapeValidator, registerValidationChecks } from './shape-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type ShapeAddedServices = {
    validation: {
        ShapeValidator: ShapeValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type ShapeServices = LangiumServices & ShapeAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const ShapeModule: Module<ShapeServices, PartialLangiumServices & ShapeAddedServices> = {
    validation: {
        ShapeValidator: () => new ShapeValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createShapeServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Shape: ShapeServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        ShapeGeneratedSharedModule
    );
    const Shape = inject(
        createDefaultModule({ shared }),
        ShapeGeneratedModule,
        ShapeModule
    );
    shared.ServiceRegistry.register(Shape);
    registerValidationChecks(Shape);
    return { shared, Shape };
}
